import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/About.module.css";
import Header from "@/components/Header/Header";
import CommonButton from "@/components/CommonBtn/CommonBtn";
import Subtitle from "@/components/Subtitle/Subtitlle";
import Heading from "@/components/Heading/Heading";
import { useState } from "react";
import { FaPlus, FaMinus } from "react-icons/fa"; // npm install react-icons
import { HiMinus, HiOutlineChevronRight } from "react-icons/hi2";
import { BsPlusLg } from "react-icons/bs";
import Footer from "@/components/Footer/Footer";
import HubspotEmbedForm from "@/components/HubspotEmbedForm/HubspotEmbedForm";

export default function About() {
    const colleges = [
        { img: "/images/lse.png", name: "LSE" },
        { img: "/images/kings.png", name: "king" },
        { img: "/images/edinburgh.png", name: "Oxford" },
        { img: "/images/glasgow.png", name: "Cambridge" },
        { img: "/images/ucl.png", name: "UCL" },
        { img: "/images/sheffield.png", name: "King’s College London" },
        { img: "/images/warwick.png", name: "Warwick" },
        { img: "/images/manchester.png", name: "Manchester" },
        { img: "/images/southampton.png", name: "southampton" },
        { img: "/images/york.png", name: "york" },
        { img: "/images/queenmarry.png", name: "queenmarry" },
        { img: "/images/newcastle-university.svg", name: "newcastle-university" },
        { img: "/images/nottingham.webp", name: "nottingham" },
        { img: "/images/belfast.jpg", name: "belfast" },
        { img: "/images/liverpool.png", name: "liverpool" },
    ];
    const [activeIndex, setActiveIndex] = useState(null);

    const faqs = [
        {
            q: "What are the basic eligibility criteria for admission to UK universities?",
            a: "Most UK universities require completion of high school (12th grade), proof of English proficiency (IELTS/TOEFL), and relevant academic transcripts."
        },
        {
            q: "How do I apply to UK universities from India?",
            a: "You can apply directly through each university’s website or via the UCAS application system for undergraduate programs."
        },
        {
            q: "What is the application deadline for UK universities?",
            a: "Deadlines vary, but most undergraduate applications through UCAS close in January, and postgraduate deadlines depend on the university and course."
        },
        {
            q: "Do UK universities accept three-year bachelor’s degrees from India for master’s programs?",
            a: "Yes, most UK universities recognize three-year bachelor’s degrees (such as BA, BCom, BSc) awarded in India."
        },
        {
            q: "What are the English language requirements for UK universities?",
            a: "Acceptable tests include IELTS, TOEFL, PTE, or Duolingo. Minimum scores depend on the university and program."
        },
        {
            q: "Can I work while studying in the UK?",
            a: "Yes, international students can work up to 20 hours per week during term time and full-time during vacations."
        },
        {
            q: "Are scholarships available for Indian students?",
            a: "Many UK universities offer merit-based scholarships and financial aid for international students, including those from India."
        },
        {
            q: "How do I arrange accommodation in the UK?",
            a: "Universities usually provide guidance and options for both on-campus and off-campus housing."
        },
        {
            q: "What is the Post-Study Work visa?",
            a: "The Graduate Route allows international students to stay and work in the UK for up to 2 years after graduation."
        },
        {
            q: "How do I obtain an education loan for studying in the UK?",
            a: "Most major Indian banks and financial institutions offer education loans for studies at recognized UK universities."
        }
    ];
    const toggle = (i) =>
        setActiveIndex(activeIndex === i ? null : i);
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* =======banner======= */}
            <section className={styles.mainBanner}>
                <div className={styles.bannerGraphics}>
                    <img src="/images/bg-graphics.png" alt="bg-graphics" />
                </div>

                <div className="container">
                    <div className={`row justify-content-center align-items-center ${styles.bannerRow}`}
                    >
                        <div className="col-lg-7">
                            <div className={styles.bannerContent}>
                                <h1>About Us</h1>
                                {/* Breadcrumb starts here */}
                                <nav aria-label="breadcrumb" className={styles.breadcrumbWrapper}>
                                    <ol className={styles.breadcrumb}>
                                        <li className={styles.breadcrumbItem}>
                                            <a href="/">Home</a>
                                            <span className={styles.chevron}><HiOutlineChevronRight /></span>
                                        </li>
                                        <li
                                            className={`${styles.breadcrumbItem} ${styles.active}`}
                                            aria-current="page"
                                        >
                                            About Us
                                        </li>
                                    </ol>
                                </nav>

                                {/* Breadcrumb ends here */}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ========about======= */}
            <section
                id="about"
                className={styles.aboutUs}
            // style={{ backgroundImage: `url("/images/about-bg.png")` }}
            >
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-6">
                            <div className={styles.thumbStyleTwo}>
                                <img
                                    className={`wow fadeInUp ${styles.image}`}
                                    src="/images/4.jpg"
                                    alt="Image Not Found"
                                />
                                <img
                                    className={`wow fadeInDown ${styles.image}`}
                                    data-wow-delay="200ms"
                                    src="/images/5.jpg"
                                    alt="Image Not Found"
                                />
                                <div className={styles.shape}>
                                    <img src="/images/35.png" alt="Image Not Found" />
                                    <img src="/images/37.png" alt="Image Not Found" />
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-6">
                            <div className={styles.aboutContent}>
                                <Subtitle text={"Who We Are"} />
                                <Heading mainText={"About Us"} />
                                <p>
                                    Eduspire Global is a name that has generated trust among
                                    students and parents for several years in the fields of both
                                    domestic and overseas education. We empower students to pursue
                                    world class education in the United Kingdom as well as several
                                    premier universities in India.Specializing in admissions
                                    abroad, we provide specialized support, expert counseling ,
                                    scholarship assistance,visa application support and
                                    orientation support.
                                </p>
                                <p>
                                    With a strong presence in major cities of India, Eduspire
                                    Global focuses on simplifying the application process, provide
                                    unbiased guidance in identifying universities and handhold
                                    students throughout the entire process of admission,
                                    scholarship, accommodation, visa and pre-departure session.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className={styles.ourStats}>
                <div className="container">
                    <div className={styles.topSec}>
                        <Subtitle text={"Education for everyone"} />
                        <Heading mainText={"Our Core Strengths"} />
                        <p>
                            Eduspire Global is dedicated to supporting aspiring students
                            throughout their application journey, from choosing the perfect
                            course to settling comfortably into university life.
                        </p>
                    </div>
                    <div className="row">
                        <div className="col-lg-4">
                            <div className={styles.eachGuidence}>
                                <div
                                    className={styles.icon}
                                    style={{ backgroundColor: "#FFEAD7" }}
                                >
                                    <img src="/images/library.png" />
                                </div>
                                <h4>Global University Tie Ups</h4>
                               <h3>50+</h3>
                            </div>
                        </div>
                        <div className="col-lg-4">
                            <div className={styles.eachGuidence}>
                                <div
                                    className={styles.icon}
                                    style={{ backgroundColor: "#E4E0FF" }}
                                >
                                    <img src="/images/portfolio.png" />
                                </div>
                                <h4>Years of Industry Presence</h4>
                                <h3>5+</h3>
                            </div>
                        </div>
                        <div className="col-lg-4">
                            <div className={styles.eachGuidence}>
                                <div
                                    className={styles.icon}
                                    style={{ backgroundColor: "#FFEAD7" }}
                                >
                                    <img src="/images/graduate-hat.png" />
                                </div>
                                <h4>Students Enrolled</h4>
                                <h3>5K</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
 {/* ==============guidence Form============ */}
      <section className={styles.guidenceForm}>
        <div className={styles.contactGraphicsOne}>
          <img src="/images/yellow.png" />
        </div>
        <div className={styles.contactGraphicsTwo}>
          <img src="/images/contact-graphics.png" />
        </div>
        <div className="container">
          <section className={styles.contactWrap}>
            <div className="row align-items-center">
              <div className="col-lg-6">
                <div className={styles.topSec}>
                  <Subtitle text={"Personalised Guidance"} />
                  <Heading
                    mainText={
                      "Get Personalised Guidance for Your UK or Ireland University Journey"
                    }
                  />
                  <p>Have questions about university admissions, course selection, or visa applications? Our experienced team at EdusoireGlobal is here to support you every step of the way. Fill out the form below and let us help you make the right choices for your future.</p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.formWrap}>
                  {/* <form className={styles.form}>
                    <div className={styles.formGroup}>
                      <label htmlFor="firstName">First Name</label>
                      <input
                        type="text"
                        id="firstName"
                        name="firstName"
                        placeholder="Enter first name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="lastName">Last Name</label>
                      <input
                        type="text"
                        id="lastName"
                        name="lastName"
                        placeholder="Enter last name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="email">Email</label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        placeholder="Enter email"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <CommonButton text={'Submit'} />
                  </form> */}
                  <HubspotEmbedForm />
                </div>

              </div>
            </div>
          </section>
        </div>
      </section>


            <Footer />

        </>
    );
}
