import Head from "next/head";
import styles from "@/styles/contact.module.css";
import Header from "@/components/Header/Header";
import CommonButton from "@/components/CommonBtn/CommonBtn";
import Subtitle from "@/components/Subtitle/Subtitlle";
import Heading from "@/components/Heading/Heading";
import { useState } from "react";
import { FaPlus, FaMinus, FaFacebookF, FaInstagram } from "react-icons/fa"; // npm install react-icons
import { HiMinus, HiOutlineChevronDoubleRight, HiOutlineChevronRight } from "react-icons/hi2";
import { BsPlusLg } from "react-icons/bs";
import Footer from "@/components/Footer/Footer";
import HubspotEmbedForm from "@/components/HubspotEmbedForm/HubspotEmbedForm";
import Link from "next/link";
import Modal from "@/components/Modal/Modal";

export default function WhyUK() {
    const [open, setOpen] = useState(false);
    return (
        <>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* =======banner======= */}
            <section className={styles.mainBanner}>
                <div className={styles.bannerGraphics}>
                    <img src="/images/bg-graphics.png" alt="bg-graphics" />
                </div>

                <div className="container">
                    <div className={`row justify-content-center align-items-center ${styles.bannerRow}`}
                    >
                        <div className="col-lg-7">
                            <div className={styles.bannerContent}>
                                <h1>Contact Us</h1>
                                {/* Breadcrumb starts here */}
                                <nav aria-label="breadcrumb" className={styles.breadcrumbWrapper}>
                                    <ol className={styles.breadcrumb}>
                                        <li className={styles.breadcrumbItem}>
                                            <a href="/">Home</a>
                                            <span className={styles.chevron}><HiOutlineChevronRight /></span>
                                        </li>
                                        <li
                                            className={`${styles.breadcrumbItem} ${styles.active}`}
                                            aria-current="page"
                                        >
                                            Contact Us
                                        </li>
                                    </ol>
                                </nav>

                                {/* Breadcrumb ends here */}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ============contact top=========== */}
            <section className={styles.contactTop}>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-4">
                            <div className={styles.contactInfoBox}>
                                <div className={styles.contactInfoIcon} style={{backgroundColor: '#FFEAD7'}}>
                                    <img src="/images/call-us-icon.svg" alt="contact-icon" />
                                </div>
                                <h4>Call Us</h4>
                                <a href="tel:9147734848">9147734848</a>
                            </div>
                        </div>
                        <div className="col-lg-4">
                            <div className={styles.contactInfoBox}>
                                <div className={styles.contactInfoIcon} style={{backgroundColor: '#D5F6E3'}}>
                                    <img src="/images/follow-us-icon.svg" alt="contact-icon" />
                                </div>
                                <h4>Follow Us</h4>
                                <ul>
                                    <li><Link target="_blank" href={"https://www.instagram.com/eduspire.global?igsh=MXdod3p2cXlkNnNvbg=="}><FaInstagram /></Link></li>
                                    <li><Link target="_blank" href={"https://www.facebook.com/share/1FWprfsJN3/"}>< FaFacebookF/></Link></li>
                                </ul>
                            </div>
                        </div>
                        <div className="col-lg-4">
                            <div className={styles.contactInfoBox}>
                                <div className={styles.contactInfoIcon} style={{backgroundColor: '#FFF7CE'}}>
                                    <img src="/images/envelop-icon.svg" alt="contact-icon" />
                                </div>
                                <h4>Follow Us</h4>
                                <a href="mailto:info@eduspireglobal.com">info@eduspireglobal.com</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ==============guidence Form============ */}
            <section className={styles.guidenceForm}>
                <div className={styles.contactGraphicsOne}>
                    <img src="/images/yellow.png" />
                </div>
                <div className={styles.contactGraphicsTwo}>
                    <img src="/images/contact-graphics.png" />
                </div>
                <div className="container">
                    <section className={styles.contactWrap}>
                        <div className="row align-items-center">
                            <div className="col-lg-6">
                                <div className={styles.topSec}>
                                    {/* <Subtitle text={"Personalised Guidance"} /> */}
                                    <Heading
                                        mainText={
                                            "Get Personalised Guidance for Your UK or Ireland University Journey"
                                        }
                                    />
                                    <p>Have questions about university admissions, course selection, or visa applications? Our experienced team at EdusoireGlobal is here to support you every step of the way. Fill out the form below and let us help you make the right choices for your future.</p>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.formWrap}>
                                    {/* <form className={styles.form}>
                    <div className={styles.formGroup}>
                      <label htmlFor="firstName">First Name</label>
                      <input
                        type="text"
                        id="firstName"
                        name="firstName"
                        placeholder="Enter first name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="lastName">Last Name</label>
                      <input
                        type="text"
                        id="lastName"
                        name="lastName"
                        placeholder="Enter last name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="email">Email</label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        placeholder="Enter email"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <CommonButton text={'Submit'} />
                  </form> */}
                                    <HubspotEmbedForm />
                                </div>

                            </div>
                        </div>
                    </section>
                </div>
            </section>

            <Footer />

        </>
    );
}
