import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import CommonButton from "@/components/CommonBtn/CommonBtn";
import Subtitle from "@/components/Subtitle/Subtitlle";
import Heading from "@/components/Heading/Heading";
import { useState } from "react";
import { FaPlus, FaMinus } from "react-icons/fa"; // npm install react-icons
import { HiMinus } from "react-icons/hi2";
import { BsPlusLg } from "react-icons/bs";
import Footer from "@/components/Footer/Footer";

export default function Home() {
  const colleges = [
    { img: "/images/lse.png", name: "LSE" },
    { img: "/images/kings.png", name: "king" },
    { img: "/images/edinburgh.png", name: "Oxford" },
    { img: "/images/glasgow.png", name: "Cambridge" },
    { img: "/images/ucl.png", name: "UCL" },
    { img: "/images/sheffield.png", name: "King’s College London" },
    { img: "/images/warwick.png", name: "Warwick" },
    { img: "/images/manchester.png", name: "Manchester" },
    { img: "/images/southampton.png", name: "southampton" },
    { img: "/images/york.png", name: "york" },
    { img: "/images/queenmarry.png", name: "queenmarry" },
    { img: "/images/newcastle-university.svg", name: "newcastle-university" },
    { img: "/images/nottingham.webp", name: "nottingham" },
    { img: "/images/belfast.jpg", name: "belfast" },
    { img: "/images/liverpool.png", name: "liverpool" },
  ];
  const [activeIndex, setActiveIndex] = useState(null);

  const faqs = [
    {
      q: "What are the basic eligibility criteria for admission to UK universities?",
      a: "Most UK universities require completion of high school (12th grade), proof of English proficiency (IELTS/TOEFL), and relevant academic transcripts."
    },
    {
      q: "How do I apply to UK universities from India?",
      a: "You can apply directly through each university’s website or via the UCAS application system for undergraduate programs."
    },
    {
      q: "What is the application deadline for UK universities?",
      a: "Deadlines vary, but most undergraduate applications through UCAS close in January, and postgraduate deadlines depend on the university and course."
    },
    {
      q: "Do UK universities accept three-year bachelor’s degrees from India for master’s programs?",
      a: "Yes, most UK universities recognize three-year bachelor’s degrees (such as BA, BCom, BSc) awarded in India."
    },
    {
      q: "What are the English language requirements for UK universities?",
      a: "Acceptable tests include IELTS, TOEFL, PTE, or Duolingo. Minimum scores depend on the university and program."
    },
    {
      q: "Can I work while studying in the UK?",
      a: "Yes, international students can work up to 20 hours per week during term time and full-time during vacations."
    },
    {
      q: "Are scholarships available for Indian students?",
      a: "Many UK universities offer merit-based scholarships and financial aid for international students, including those from India."
    },
    {
      q: "How do I arrange accommodation in the UK?",
      a: "Universities usually provide guidance and options for both on-campus and off-campus housing."
    },
    {
      q: "What is the Post-Study Work visa?",
      a: "The Graduate Route allows international students to stay and work in the UK for up to 2 years after graduation."
    },
    {
      q: "How do I obtain an education loan for studying in the UK?",
      a: "Most major Indian banks and financial institutions offer education loans for studies at recognized UK universities."
    }
  ];
  const toggle = (i) =>
    setActiveIndex(activeIndex === i ? null : i);
  return (
    <>
      <Head>
        <title>Eduspireglobal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* =======banner======= */}
      <section
        className={styles.mainBanner}
      >
        <div class={styles.bannerGraphics}>
          <img src="/images/bg-graphics.png" alt="bg-graphics" />
        </div>
       
        <div className="container">
          <h1>
            Expert Guidance for UK & 
            Ireland <span> University Admissions</span>
          </h1>
          <div className="row align-items-center">
            <div className="col-lg-7">
              <div className={styles.bannerContent}>

                <p>
                  At Eduspire Global, we specialise in helping aspiring students
                  successfully secure admissions at leading universities in the
                  UK and Ireland. Our team offers comprehensive support
                  throughout your academic journey, including course and
                  university selection, expert financial advice, assistance with
                  VISA applications, accommodation arrangements, and
                  pre-departure orientation. Trust us to help you make informed
                  decisions and embark on your international education with
                  confidence.
                </p>
                <p>
                  Meet our British Council Certified Counsellors who will
                  provide personalised Counselling sessions and Expert guidance
                  for Admissions in U.K. and Ireland. Please book an appointment
                  to avail the complimentary sessions.
                </p>
                <span>Call us for online appointment on 9147734848 </span>
                <div className={styles.bannerButton}>
                  <CommonButton className={styles.headerBtn} text={"Start Your Application"} href="#" />
                  <CommonButton className={styles.headerBtn} text={"Speak to an Advisor"} href="#" />
                </div>
              </div>
            </div>
            <div className="col-lg-5">
              <div className={styles.bannerRight}>
                <img src="/images/bannerBg.jpg" alt="banner bg" />
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* ========about======= */}
      <section
        className={styles.aboutUs}
        style={{ backgroundImage: `url("/images/about-bg.png")` }}
      >
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <div className={styles.aboutImg}>
                <img src="/images/about-img.png" alt="about image" />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.aboutContent}>
                <Subtitle text={"Who We Are"} />
                <Heading mainText={"About Us"} />
                <p>
                  Eduspire Global is a name that has generated trust among
                  students and parents for several years in the fields of both
                  domestic and overseas education. We empower students to pursue
                  world class education in the United Kingdom as well as several
                  premier universities in India.Specializing in admissions
                  abroad, we provide specialized support, expert counseling ,
                  scholarship assistance,visa application support and
                  orientation support.
                </p>
                <p>
                  With a strong presence in major cities of India, Eduspire
                  Global focuses on simplifying the application process, provide
                  unbiased guidance in identifying universities and handhold
                  students throughout the entire process of admission,
                  scholarship, accommodation, visa and pre-departure session.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* =======why us========= */}
      <section className={styles.whyUs}>
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <div className={styles.leftHeading}>
                <Subtitle text={"Why Us"} />
                <Heading
                  mainText={
                    "The United Kingdom : a century long destination for Indian students"
                  }
                />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.rightItem}>
                <p>
                  For over 100 years, United Kingdom has been a steadfast choice
                  for Indian students. The endless appeal of United Kingdom lies
                  not merely in prestige and ranking, but also in the seamless
                  confluence of quality, research and job opportunity.
                </p>
                <p>
                  From the hallowed halls of Oxford, Cambridge, LSE and Imperial
                  to the esteemed institutions like Manchester, Warwick,
                  Glasgow, Edinburgh, SOAS, Kings College London...consistently
                  rank among top 500 universities globally.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#FFEAD7" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Strong academic synergy with India</h4>
                  <p>
                    The Indian education system has many similarities with UK's
                    academic framework. UK universities highly recognise the
                    three year undergraduate academic degree program (BSc, BCom,
                    BA, BBA, BCA), which are often not accepted in countries
                    like USA. Similarly for undergraduate admissions, CBSE, ISC
                    and state boards are accepted alongside international
                    curriculum like A levels and IB,
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#D5F6E3" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Time efficient and cost effective degree</h4>
                  <p>
                    Bachelor's degrees usually takes three years Master degree
                    programs are typically one year, saving both on tuition fees
                    and living expenses.PHD programs span 3 years
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#E4E0FF" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Multicultural student community</h4>
                  <p>
                    With students from over 130 countries, international
                    students can work upto 20 hours per week during term time
                    and gain ample exposure to the local culture and thought
                    process.
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#FFD7D8" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Financial support and post study work</h4>
                  <p>
                    All UK universities are recognised by Indian financial
                    institutions (both government and private). That makes it
                    easy for Indian students to get education loans. The
                    Post-Study Work visa allows international students to stay
                    back and work in UK for upto 2 years, after completion of
                    student visa. That gives international students ample
                    international work experience and exposure and thus empowers
                    students to take assured steps towards a global future.
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* =======partener====== */}
      <section className={styles.universities}>
        <div className="container">
          <div className={styles.topSec}>
            <Subtitle text={"Our Partner"} />
            <Heading mainText={"Some of the Universities We Represent"} />
            <p>
              Eduspire Global is dedicated to supporting aspiring students
              throughout their application journey, from choosing the perfect
              course to settling comfortably into university life.
            </p>
          </div>
          <div className="row justify-content-center">
            {colleges.map((college, index) => (
              <div key={index} className="col-lg-3 col-md-4 col-sm-6 mb-4">
                <div className={styles.eachCollege}>
                  <img src={college.img} alt={college.name} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =======expert guidence====== */}
      <section className={styles.guidence}>
        <div className="container">
          <div className={styles.topSec}>
            <Subtitle text={"Our Guidance"} />
            <Heading
              mainText={
                "Expert Guidance for Your UK & Ireland University Journey"
              }
            />
          </div>
          <div className="row justify-content-center">
            <div className="col-lg-4">
              <div className={styles.eachGuidence}>
                <div
                  className={styles.icon}
                  style={{ backgroundColor: "#FFEAD7" }}
                >
                  <img src="/images/icon1.svg" />
                </div>
                <h4>Comprehensive Course & University Selection</h4>
                <p>
                  Our experienced advisors assist you in identifying the right
                  course and university, tailored to your interests and
                  long-term career aspirations. We provide in-depth information
                  and personalised recommendations to ensure you make the best
                  decision for your future.
                </p>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachGuidence}>
                <div
                  className={styles.icon}
                  style={{ backgroundColor: "#E4E0FF" }}
                >
                  <img src="/images/icon8.svg" />
                </div>
                <h4>Financial Guidance & VISA Application Support</h4>
                <p>
                  Navigating tuition fees, scholarships, and budgeting can be
                  complex. Eduspire Global offers expert financial guidance,
                  helping you understand your options and prepare a strong VISA
                  application, making the process smooth and stress-free.
                </p>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachGuidence}>
                <div
                  className={styles.icon}
                  style={{ backgroundColor: "#D5F6E3" }}
                >
                  <img src="/images/icon7.svg" />
                </div>
                <h4>Accommodation & Orientation Assistance</h4>
                <p>
                  We go beyond admissions by helping you secure suitable
                  accommodation and offering orientation guidance. Our support
                  ensures you start your academic journey in the UK or Ireland
                  with confidence and peace of mind.
                </p>
              </div>
            </div>
          </div>
          <div
            className={styles.serviceArea}
            style={{ backgroundImage: `url("/images/green-bg-shape.png")` }}
          >
            <Subtitle text={"Our Service"} />
            <Heading
              className={styles.serviceHeading}
              mainText={"Our service is recognised by British Council"}
            />
            <p>
              Experience our unified support solution—designed to empower you at
              every stage of your journey. This comprehensive offering combines
              proactive guidance, personalised support, and exemplary service
              into one seamless experience. Our certified counsellors,
              accredited by the British Council, provide expert assistance from
              initial onboarding through ongoing optimisation. This ensures you
              receive, adopt, utilise, and benefit from the Eduspire Global
              approach. Benefit from direct access to industry specialists,
              tailored strategic advice, and priority access to advanced
              resources and troubleshooting. Our dedicated team partners with
              you to address evolving needs, integrated approach, continuous
              support, and strategic recommendations to achieve your goal. With
              this all-in-one service, you move forward knowing you have the
              full strength of Eduspire Global behind you—supporting, guiding,
              and helping you achieve your goals every step of the way.
            </p>
            <ul>
              <li>Initial consultation and profile assessment</li>
              <li>Personalised university and course shortlisting</li>
              <li>Application guidance for universities</li>
              <li>Personalised support throughout the process</li>
              <li>Complete VISA assistance</li>
              <li>Building connections with ALUMNI</li>
            </ul>
          </div>
        </div>
      </section>

      {/* =======educational guidence====== */}
      <section className={styles.educationalJourney}>
        <div className="container">
          <div className={`${"row align-items-center"} ${styles.row}`}>
            <div className="col-lg-6">
              <div className={styles.journeyDetails}>
                <div className={styles.topSec}>
                  <Subtitle text={"Education Journey"} />
                  <Heading
                    mainText={
                      "Empowering Your Global Education Journey"
                    }
                  />
                  <p>At Eduspire Global, we specialise in guiding aspiring students through every step of the university admissions process for the UK and Ireland. Our expert team offers personalised support, from course and university selection to financial advice, VISA application assistance, accommodation arrangements, and pre-departure orientation. With a student-focused approach, we ensure you are equipped with the right information and resources to make confident decisions about your future.</p>
                </div>
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.journeyImg}>
                <img src="/images/students.jpg" />
              </div>
            </div>
          </div>
          <div className={`${"row align-items-center"} ${styles.row}`}>
            <div className="col-lg-6">
              <div className={styles.journeyDetails}>
                <div className={styles.topSec}>
                  <Subtitle text={"Our Support "} />
                  <Heading
                    mainText={
                      "Our Comprehensive Student Support Services"
                    }
                  />
                  <p>At Eduspire Global, we specialise in guiding aspiring students through every stage of their academic journey to the UK and Ireland. Our expert team offers personalised support with course and university selection, ensuring you make choices that align with your ambitions. We also provide financial guidance, assist with VISA applications, and help secure suitable accommodation. From your initial enquiry to your arrival and orientation, EdusoireGlobal is committed to making your transition smooth and successful.</p>
                </div>
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.journeyImg}>
                <img src="/images/support.jpg" />
              </div>
            </div>
          </div>

        </div>
      </section>

      {/* ==============guidence Form============ */}
      <section className={styles.guidenceForm}>
        <div className={styles.contactGraphicsOne}>
          <img src="/images/yellow.png" />
        </div>
        <div className={styles.contactGraphicsTwo}>
          <img src="/images/contact-graphics.png" />
        </div>
        <div className="container">
          <section className={styles.contactWrap}>
            <div className="row align-items-center">
              <div className="col-lg-6">
                <div className={styles.topSec}>
                  <Subtitle text={"Personalised Guidance"} />
                  <Heading
                    mainText={
                      "Get Personalised Guidance for Your UK or Ireland University Journey"
                    }
                  />
                  <p>Have questions about university admissions, course selection, or visa applications? Our experienced team at EdusoireGlobal is here to support you every step of the way. Fill out the form below and let us help you make the right choices for your future.</p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.formWrap}>
                  <form className={styles.form}>
                    <div className={styles.formGroup}>
                      <label htmlFor="firstName">First Name</label>
                      <input
                        type="text"
                        id="firstName"
                        name="firstName"
                        placeholder="Enter first name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="lastName">Last Name</label>
                      <input
                        type="text"
                        id="lastName"
                        name="lastName"
                        placeholder="Enter last name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="email">Email</label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        placeholder="Enter email"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <CommonButton text={'Submit'} />
                  </form>
                </div>

              </div>
            </div>
          </section>
        </div>
      </section>

      {/* ============student support========== */}
      <section className={styles.studentSupport}>
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-10">
              <div className={styles.topSec}>
                <Subtitle text={"Student Support"} />
                <Heading
                  mainText={
                    "Comprehensive Student Support for UK & Ireland University Admissions"
                  }
                />
                <p>At Eduspire Global, we specialise in guiding aspiring students through every stage of the university admission process in the UK and Ireland. Our expert team offers personalised assistance with course and university selection, ensuring that each student chooses the path best suited to their ambitions and interests. We provide comprehensive financial guidance, support with VISA applications, and advice on securing accommodation. From initial orientation to settling in, EduspireGlobal is committed to making your international education journey seamless and successful.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ==============faq=================== */}
      <section className={styles.faq}>
        <div className="container">
          <div className={styles.topSec}>
            <Subtitle text={"Quick Answer"} />
            <Heading
              mainText={
                "Frequently Asked Questions"
              }
            />
          </div>
          <div className={styles.accordWrap}>
            {faqs.map((item, i) => (
              <div key={i} className={styles.accordItem}>
                <div className={styles.accordHeader} onClick={() => toggle(i)}>
                  <span className={styles.accordNumber}>{i + 1}</span>
                  <span className={styles.accordTitle}>{item.q}</span>
                  <span className={styles.accordIcon}>
                    {activeIndex === i ? <HiMinus /> : <BsPlusLg />}
                  </span>
                </div>
                {activeIndex === i && (
                  <div className={styles.accordContent}>
                    <p>{item.a}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      <Footer />

    </>
  );
}
