import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import CommonButton from "@/components/CommonBtn/CommonBtn";
import Subtitle from "@/components/Subtitle/Subtitlle";
import Heading from "@/components/Heading/Heading";

export default function Home() {
  const colleges = [
    { img: "/images/lse.png", name: "LSE" },
    { img: "/images/kings.png", name: "king" },
    { img: "/images/edinburgh.png", name: "Oxford" },
    { img: "/images/glasgow.png", name: "Cambridge" },
    { img: "/images/ucl.png", name: "UCL" },
    { img: "/images/sheffield.png", name: "King’s College London" },
    { img: "/images/warwick.png", name: "Warwick" },
    { img: "/images/manchester.png", name: "Manchester" },
    { img: "/images/southampton.png", name: "southampton" },
    { img: "/images/york.png", name: "york" },
    { img: "/images/queenmarry.png", name: "queenmarry" },
    { img: "/images/newcastle-university.svg", name: "newcastle-university" },
    { img: "/images/nottingham.webp", name: "nottingham" },
    { img: "/images/belfast.jpg", name: "belfast" },
    { img: "/images/liverpool.png", name: "liverpool" },
  ];
  return (
    <>
      <Head>
        <title>Eduspireglobal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* =======banner======= */}
      <section
        className={styles.mainBanner}
        style={{ backgroundImage: `url("/images/banner.jpg")` }}
      >
        <div className="container">
          <div className="row">
            <div className="col-lg-7">
              <div className={styles.bannerContent}>
                <h1>
                  Expert Guidance for UK & <br />
                  Ireland <span> University Admissions</span>
                </h1>
                <p>
                  At Eduspire Global, we specialise in helping aspiring students
                  successfully secure admissions at leading universities in the
                  UK and Ireland. Our team offers comprehensive support
                  throughout your academic journey, including course and
                  university selection, expert financial advice, assistance with
                  VISA applications, accommodation arrangements, and
                  pre-departure orientation. Trust us to help you make informed
                  decisions and embark on your international education with
                  confidence.
                </p>
                <div className={styles.bannerButton}>
                  <CommonButton text={"Start Your Application"} href="#" />
                  <CommonButton text={"Speak to an Advisor"} href="#" />
                </div>
              </div>
            </div>
            <div className="col-lg-5">
              <div className={styles.bannerRight}>
                <h4>Let us help you</h4>
                <p>
                  Meet our British Council Certified Counsellors who will
                  provide personalised Counselling sessions and Expert guidance
                  for Admissions in U.K. and Ireland. Please book an appointment
                  to avail the complimentary sessions.
                </p>
                <span>Call us for online appointment on 9147734848 </span>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* ========about======= */}
      <section
        className={styles.aboutUs}
        style={{ backgroundImage: `url("/images/about-bg.png")` }}
      >
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <div className={styles.aboutImg}>
                <img src="/images/about-img.png" alt="about image" />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.aboutContent}>
                <Subtitle text={"Who We Are"} />
                <Heading mainText={"About Us"} />
                <p>
                  Eduspire Global is a name that has generated trust among
                  students and parents for several years in the fields of both
                  domestic and overseas education. We empower students to pursue
                  world class education in the United Kingdom as well as several
                  premier universities in India.Specializing in admissions
                  abroad, we provide specialized support, expert counseling ,
                  scholarship assistance,visa application support and
                  orientation support.
                </p>
                <p>
                  With a strong presence in major cities of India, Eduspire
                  Global focuses on simplifying the application process, provide
                  unbiased guidance in identifying universities and handhold
                  students throughout the entire process of admission,
                  scholarship, accommodation, visa and pre-departure session.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* =======why us========= */}
      <section className={styles.whyUs}>
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <div className={styles.leftHeading}>
                <Subtitle text={"Why Us"} />
                <Heading
                  mainText={
                    "The United Kingdom : a century long destination for Indian students"
                  }
                />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.rightItem}>
                <p>
                  For over 100 years, United Kingdom has been a steadfast choice
                  for Indian students. The endless appeal of United Kingdom lies
                  not merely in prestige and ranking, but also in the seamless
                  confluence of quality, research and job opportunity.
                </p>
                <p>
                  From the hallowed halls of Oxford, Cambridge, LSE and Imperial
                  to the esteemed institutions like Manchester, Warwick,
                  Glasgow, Edinburgh, SOAS, Kings College London...consistently
                  rank among top 500 universities globally.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#FFEAD7" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Strong academic synergy with India</h4>
                  <p>
                    The Indian education system has many similarities with UK's
                    academic framework. UK universities highly recognise the
                    three year undergraduate academic degree program (BSc, BCom,
                    BA, BBA, BCA), which are often not accepted in countries
                    like USA. Similarly for undergraduate admissions, CBSE, ISC
                    and state boards are accepted alongside international
                    curriculum like A levels and IB,
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#D5F6E3" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Time efficient and cost effective degree</h4>
                  <p>
                    Bachelor's degrees usually takes three years Master degree
                    programs are typically one year, saving both on tuition fees
                    and living expenses.PHD programs span 3 years
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#E4E0FF" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Multicultural student community</h4>
                  <p>
                    With students from over 130 countries, international
                    students can work upto 20 hours per week during term time
                    and gain ample exposure to the local culture and thought
                    process.
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.eachItem} style={{ backgroundColor: "#FFD7D8" }}>
          <div className="container">
            <div className={`${"row align-items-center"} ${styles.row}`}>
              <div className="col-lg-6">
                <div className={styles.whyContent}>
                  <h4>Financial support and post study work</h4>
                  <p>
                    All UK universities are recognised by Indian financial
                    institutions (both government and private). That makes it
                    easy for Indian students to get education loans. The
                    Post-Study Work visa allows international students to stay
                    back and work in UK for upto 2 years, after completion of
                    student visa. That gives international students ample
                    international work experience and exposure and thus empowers
                    students to take assured steps towards a global future.
                  </p>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.eachImg}>
                  <img src="/images/whyus.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* =======partener====== */}
      <section className={styles.universities}>
        <div className="container">
          <div className={styles.topSec}>
            <Subtitle text={"Our Partner"} />
            <Heading mainText={"Some of the Universities We Represent"} />
            <p>
              Eduspire Global is dedicated to supporting aspiring students
              throughout their application journey, from choosing the perfect
              course to settling comfortably into university life.
            </p>
          </div>
          <div className="row justify-content-center">
            {colleges.map((college, index) => (
              <div key={index} className="col-lg-3 col-md-4 col-sm-6 mb-4">
                <div className={styles.eachCollege}>
                  <img src={college.img} alt={college.name} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =======expert guidence====== */}
      <section className={styles.guidence}>
        <div className="container">
          <div className={styles.topSec}>
            <Subtitle text={"Our Guidance"} />
            <Heading
              mainText={
                "Expert Guidance for Your UK & Ireland University Journey"
              }
            />
          </div>
          <div className="row justify-content-center">
            <div className="col-lg-4">
              <div className={styles.eachGuidence}>
                <div
                  className={styles.icon}
                  style={{ backgroundColor: "#FFEAD7" }}
                >
                  <img src="/images/icon1.svg" />
                </div>
                <h4>Comprehensive Course & University Selection</h4>
                <p>
                  Our experienced advisors assist you in identifying the right
                  course and university, tailored to your interests and
                  long-term career aspirations. We provide in-depth information
                  and personalised recommendations to ensure you make the best
                  decision for your future.
                </p>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachGuidence}>
                <div
                  className={styles.icon}
                  style={{ backgroundColor: "#E4E0FF" }}
                >
                  <img src="/images/icon8.svg" />
                </div>
                <h4>Financial Guidance & VISA Application Support</h4>
                <p>
                  Navigating tuition fees, scholarships, and budgeting can be
                  complex. Eduspire Global offers expert financial guidance,
                  helping you understand your options and prepare a strong VISA
                  application, making the process smooth and stress-free.
                </p>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachGuidence}>
                <div
                  className={styles.icon}
                  style={{ backgroundColor: "#D5F6E3" }}
                >
                  <img src="/images/icon7.svg" />
                </div>
                <h4>Accommodation & Orientation Assistance</h4>
                <p>
                  We go beyond admissions by helping you secure suitable
                  accommodation and offering orientation guidance. Our support
                  ensures you start your academic journey in the UK or Ireland
                  with confidence and peace of mind.
                </p>
              </div>
            </div>
          </div>
          <div
            className={styles.serviceArea}
            style={{ backgroundImage: `url("/images/green-bg-shape.png")` }}
          >
            <Subtitle text={"Our Service"} />
            <Heading
              className={styles.serviceHeading}
              mainText={"Our service is recognised by British Council"}
            />
            <p>
              Experience our unified support solution—designed to empower you at
              every stage of your journey. This comprehensive offering combines
              proactive guidance, personalised support, and exemplary service
              into one seamless experience. Our certified counsellors,
              accredited by the British Council, provide expert assistance from
              initial onboarding through ongoing optimisation. This ensures you
              receive, adopt, utilise, and benefit from the Eduspire Global
              approach. Benefit from direct access to industry specialists,
              tailored strategic advice, and priority access to advanced
              resources and troubleshooting. Our dedicated team partners with
              you to address evolving needs, integrated approach, continuous
              support, and strategic recommendations to achieve your goal. With
              this all-in-one service, you move forward knowing you have the
              full strength of Eduspire Global behind you—supporting, guiding,
              and helping you achieve your goals every step of the way.
            </p>
            <ul>
              <li>Initial consultation and profile assessment</li>
              <li>Personalised university and course shortlisting</li>
              <li>Application guidance for universities</li>
              <li>Personalised support throughout the process</li>
              <li>Complete VISA assistance</li>
              <li>Building connections with ALUMNI</li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
}
