import Head from "next/head";
import styles from "@/styles/scholarships.module.css";
import Header from "@/components/Header/Header";
import Subtitle from "@/components/Subtitle/Subtitlle";
import Heading from "@/components/Heading/Heading";
import { HiOutlineChevronRight } from "react-icons/hi2";
import Footer from "@/components/Footer/Footer";
import HubspotEmbedForm from "@/components/HubspotEmbedForm/HubspotEmbedForm";
import CommonButton from "@/components/CommonBtn/CommonBtn";
import { PiStudentLight } from "react-icons/pi";

export default function ScholarShips() {


    return (
        <>
            <Head>
                <title>Scholarships</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* =======banner======= */}
            <section className={styles.mainBanner}>
                <div className={styles.bannerGraphics}>
                    <img src="/images/bg-graphics.png" alt="bg-graphics" />
                </div>

                <div className="container">
                    <div className={`row justify-content-center align-items-center ${styles.bannerRow}`}
                    >
                        <div className="col-lg-7">
                            <div className={styles.bannerContent}>
                                <h1>Scholarships</h1>
                                {/* Breadcrumb starts here */}
                                <nav aria-label="breadcrumb" className={styles.breadcrumbWrapper}>
                                    <ol className={styles.breadcrumb}>
                                        <li className={styles.breadcrumbItem}>
                                            <a href="/">Home</a>
                                            <span className={styles.chevron}><HiOutlineChevronRight /></span>
                                        </li>
                                        <li
                                            className={`${styles.breadcrumbItem} ${styles.active}`}
                                            aria-current="page"
                                        >
                                            Scholarships
                                        </li>
                                    </ol>
                                </nav>

                                {/* Breadcrumb ends here */}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ========what we offer=========== */}
            <section className={styles.whatWeOffer}>
                {/* <img className={styles.hatImg} src="/images/hat.png" alt="hat" /> */}
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-7">
                            <div className={styles.whatWeOfferLeft}>
                                <div className={styles.topSec}>
                                    <Subtitle text={"Scholarship Programmes"} />
                                    <Heading
                                        className={styles.serviceHeading}
                                        mainText={"UK Scholarship Programmes: Turning Academic Dreams into Reality"}
                                    />
                                    <p>
                                        Earning a prestigious degree from the UK is a transformative journey that enriches your academic foundation and elevates your employability to new heights.
                                    </p>
                                    <p>The UK offers a wide range of funding options for international students. You can apply for scholarships, bursaries, and grants that help reduce the cost of studying abroad. Funding may be partially supported, covering a portion of your tuition fees, or fully funded, including tuition fees, living expenses, and sometimes return flights to the UK. </p>

                                </div>
                                <div className={styles.bannerButton}>

                                    <CommonButton className={styles.headerBtn} text={"Get Started"} href="#" />
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-5">
                            <div className={styles.whatWeRight}>
                                <img className={styles.rightImg} src="/images/image-01.png" alt="hat" />
                            </div>
                        </div>
                    </div>

                </div>
            </section>

            <section className={styles.costs}>
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-6">
                            <div className={styles.scolarLeft}>
                                <img src="/images/choose-us-image-01.png" alt="cost" />
                            </div>
                        </div>
                        <div className="col-lg-6">
                            <div className={styles.scolarRight}>
                                <div className={styles.topSec}>
                                    <Subtitle text={"Financial aid"} />
                                    <Heading
                                        className={styles.serviceHeading}
                                        mainText={"Empowering students through scholarships"}
                                    />
                                    <p>The UK government offers a range of prestigious scholarship programmes designed to support international students in funding their studies. These scholarships provide financial assistance for tuition fees, living expenses, and other study-related costs, helping talented students from around the world pursue their academic goals in the UK.  The UK government administers three principal scholarship programmes, namely:</p>

                                </div>
                                <ul>
                                    <li>
                                        <div className={styles.iconCircle}>
                                            <img src="/images/scholar.png" alt="great" />
                                        </div>
                                        <p>GREAT scholarships</p></li>
                                    <li>
                                        <div className={styles.iconCircle}>
                                            <img src="/images/scholar.png" alt="great" />
                                        </div>
                                        <p>Chevening scholarships</p>
                                    </li>
                                    <li>
                                        <div className={styles.iconCircle}>
                                            <img src="/images/scholar.png" alt="great" />
                                        </div>
                                        <p>Commonwealth scholarships.</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>


            {/* =======university scolarship========= */}
            <section className={styles.universityScolarship}>
                <div className="container">
                    <div className={styles.topSec}>
                        <Subtitle text={"University Scholarships"} />
                        <Heading
                            className={styles.serviceHeading}
                            mainText={"University Scholarships in the UK"}
                        />
                        <p>Many UK universities offer their own scholarship programmes to attract talented international students. These scholarships can be merit-based, need-based, or specific to certain courses or fields of study. University scholarships often cover a portion of tuition fees and may also include living expenses.</p>
                    </div>
                    <div className="row">
                        <div className="col-lg-3 col-md-6">
                            <div className={styles.socholarshipBox}>
                                <div className={styles.eachIconWrap} style={{ backgroundColor: "#FFEAD7" }}>
                                    <PiStudentLight />
                                </div>
                                <h5>Academic, Merit, and Excellence Scholarships</h5>
                                <p>Granted to students with outstanding academic achievements and consistently high grades.</p>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                            <div className={styles.socholarshipBox}>
                                <div className={styles.eachIconWrap} style={{ backgroundColor: "#D5F6E3" }}>
                                    <PiStudentLight />
                                </div>
                                <h5>Performance-Based Scholarships</h5>
                                <p>Designed for students who demonstrate exceptional talent in extracurricular fields such as sports, music, drama, or dance.</p>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                            <div className={styles.socholarshipBox}>
                                <div className={styles.eachIconWrap} style={{ backgroundColor: "#E4E0FF" }}>
                                    <PiStudentLight />
                                </div>
                                <h5>Subject-Specific Scholarships</h5>
                                <p>Offered by individual departments to students pursuing studies in particular disciplines or fields of interest.</p>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                            <div className={styles.socholarshipBox}>
                                <div className={styles.eachIconWrap} style={{ backgroundColor: "#FFF7CE" }}>
                                    <PiStudentLight />
                                </div>
                                <h5>Disability Scholarships</h5>
                                <p>These scholarships are designed to support international students with disabilities, long-term mental health conditions, learning differences, or other specific accessibility needs.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ==============guidence Form============ */}
            <section className={styles.guidenceForm}>
                <div className={styles.contactGraphicsOne}>
                    <img src="/images/yellow.png" />
                </div>
                <div className={styles.contactGraphicsTwo}>
                    <img src="/images/contact-graphics.png" />
                </div>
                <div className="container">
                    <section className={styles.contactWrap}>
                        <div className="row align-items-center">
                            <div className="col-lg-6">
                                <div className={styles.topSec}>
                                    <Subtitle text={"Future Build"} />
                                    <Heading
                                        mainText={
                                            "Let’s Plan Your Future Together"
                                        }
                                    />
                                    <p>At Eduspire Global, we believe that financial uncertainty should never stand in the way of your dreams. Our team of experts helps you plan your finances, access scholarships and loans, and confidently embark on your study abroad journey.</p>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.formWrap}>
                                    {/* <form className={styles.form}>
                    <div className={styles.formGroup}>
                      <label htmlFor="firstName">First Name</label>
                      <input
                        type="text"
                        id="firstName"
                        name="firstName"
                        placeholder="Enter first name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="lastName">Last Name</label>
                      <input
                        type="text"
                        id="lastName"
                        name="lastName"
                        placeholder="Enter last name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="email">Email</label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        placeholder="Enter email"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <CommonButton text={'Submit'} />
                  </form> */}
                                    <HubspotEmbedForm />
                                </div>

                            </div>
                        </div>
                    </section>
                </div>
            </section>
            <Footer />

        </>
    );
}
