import Head from "next/head";
import styles from "@/styles/scholarships.module.css";
import Header from "@/components/Header/Header";
import Subtitle from "@/components/Subtitle/Subtitlle";
import Heading from "@/components/Heading/Heading";
import {HiOutlineChevronRight } from "react-icons/hi2";
import Footer from "@/components/Footer/Footer";
import HubspotEmbedForm from "@/components/HubspotEmbedForm/HubspotEmbedForm";
import CommonButton from "@/components/CommonBtn/CommonBtn";

export default function ScholarShips() {
   

    return (
        <>
            <Head>
                <title>Scholarships</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* =======banner======= */}
            <section className={styles.mainBanner}>
                <div className={styles.bannerGraphics}>
                    <img src="/images/bg-graphics.png" alt="bg-graphics" />
                </div>

                <div className="container">
                    <div className={`row justify-content-center align-items-center ${styles.bannerRow}`}
                    >
                        <div className="col-lg-7">
                            <div className={styles.bannerContent}>
                                <h1>Scholarships</h1>
                                {/* Breadcrumb starts here */}
                                <nav aria-label="breadcrumb" className={styles.breadcrumbWrapper}>
                                    <ol className={styles.breadcrumb}>
                                        <li className={styles.breadcrumbItem}>
                                            <a href="/">Home</a>
                                            <span className={styles.chevron}><HiOutlineChevronRight /></span>
                                        </li>
                                        <li
                                            className={`${styles.breadcrumbItem} ${styles.active}`}
                                            aria-current="page"
                                        >
                                            Scholarships
                                        </li>
                                    </ol>
                                </nav>

                                {/* Breadcrumb ends here */}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ========what we offer=========== */}
            <section className={styles.whatWeOffer}>
                {/* <img className={styles.hatImg} src="/images/hat.png" alt="hat" /> */}
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-7">
                            <div className={styles.whatWeOfferLeft}>
                                <div className={styles.topSec}>
                                    <Subtitle text={"Scholarship Programmes"} />
                                    <Heading
                                        className={styles.serviceHeading}
                                        mainText={"UK Scholarship Programmes: Turning Academic Dreams into Reality"}
                                    />
                                    <p>
                                        Earning a prestigious degree from the UK is a transformative journey that enriches your academic foundation and elevates your employability to new heights.
                                    </p>
                                    <p>The UK offers a wide range of funding options for international students. You can apply for scholarships, bursaries, and grants that help reduce the cost of studying abroad. Funding may be partially supported, covering a portion of your tuition fees, or fully funded, including tuition fees, living expenses, and sometimes return flights to the UK. </p>

                                </div>
                                <div className={styles.bannerButton}>

                                    <CommonButton className={styles.headerBtn} text={"Get Started"} href="#" />
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-5">
                            <div className={styles.whatWeRight}>
                                <img className={styles.rightImg} src="/images/students-group.jpg" alt="hat" />
                            </div>
                        </div>
                    </div>

                </div>
            </section>

            <section className={styles.costs}>
                <div className="container">
                    {/* <img src="/images/54.png" className={styles.shape} /> */}
                    <div className={styles.topSec}>
                        <Subtitle text={"Financial aid"} />
                        <Heading
                            className={styles.serviceHeading}
                            mainText={"Empowering students through scholarships"}
                        />
                        <p>The UK government offers a range of prestigious scholarship programmes designed to support international students in funding their studies. These scholarships provide financial assistance for tuition fees, living expenses, and other study-related costs, helping talented students from around the world pursue their academic goals in the UK.  The UK government administers three principal scholarship programmes, namely:</p>
                    </div>
                    <div className="row justify-content-center">
                        <div className="col-lg-3">
                            <div className={styles.socholarshipBox}>
                                <div  className={styles.uniImg} >
                                    <img src="/images/bc.png" />
                                </div>
                                <h5>GREAT scholarships</h5>                                
                            </div>
                        </div>    
                        <div className="col-lg-3">
                            <div className={styles.socholarshipBox}>
                                <div  className={styles.uniImg} >
                                    <img src="/images/chevening.png" />
                                </div>
                                <h5>chevening scholarships</h5>                                
                            </div>
                        </div>  
                        <div className="col-lg-3">
                            <div className={styles.socholarshipBox}>
                                <div  className={styles.uniImg} >
                                    <img src="/images/commonwealth.jpg" />
                                </div>
                                <h5>Commonwealth scholarships</h5>                                
                            </div>
                        </div>                     
                    </div>
                </div>
            </section>

            {/* =======why us========= */}
            <section className={styles.whyUs}>

                <div className={styles.eachItem} style={{ backgroundColor: "#FFEAD7" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Financial Planning Tips</h4>
                                    <p>
                                        A solid financial plan can help you navigate the expenses of studying abroad with confidence. Here’s how Eduspire Global supports you at every step:
                                    </p>
                                    <ul>
                                        <li>Create a comprehensive budget covering tuition, accommodation, living costs, and additional expenses</li>
                                        <li>Explore scholarships, grants, and bursaries offered by universities, governments, and private organizations</li>
                                        <li>Understand loan options and work with banks or financial institutions to access education loans at competitive rates</li>
                                        <li>Plan for currency fluctuations and additional hidden costs such as travel, deposits, and emergency funds</li>
                                        <li>Track expenses with budgeting tools and maintain financial discipline throughout your stay abroad</li>
                                    </ul>

                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-4.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.eachItem} style={{ backgroundColor: "#D5F6E3" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Scholarships and Financial Aid</h4>
                                    <p>
                                        Many universities in the UK and Ireland offer scholarships based on merit, need, or specific fields of study. Government and international organizations also provide funding to help students reduce tuition and living costs.
                                    </p>
                                    <p>Our advisors will guide you through:</p>
                                    <ul>
                                        <li>Finding scholarships that fit your profile</li>
                                        <li>Preparing strong applications for scholarships and grants</li>
                                        <li>Meeting deadlines and submitting required documents</li>
                                    </ul>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-1.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.eachItem} style={{ backgroundColor: "#E4E0FF" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Student Loans and Funding Support</h4>
                                    <p>
                                        Education loans are a viable option to finance your studies. We help you:
                                    </p>
                                    <ul>
                                        <li>Compare loan providers and interest rates</li>
                                        <li>Understand repayment terms</li>
                                        <li>Prepare the necessary documentation for loan applications</li>
                                    </ul>
                                    <p>We work with trusted banks and financial partners to ensure you have access to reliable funding solutions.</p>

                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-2.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.eachItem} style={{ backgroundColor: "#FFD7D8" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Why Financial Planning Matters</h4>
                                    <p>Proper planning allows you to:
                                    </p>
                                    <ul>
                                        <li>Avoid last-minute surprises</li>
                                        <li>Focus on studies rather than money worries</li>
                                        <li>Make informed decisions about housing, lifestyle, and extracurricular activities</li>
                                        <li>Build healthy financial habits for long-term success</li>
                                    </ul>

                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-3.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* ==============guidence Form============ */}
            <section className={styles.guidenceForm}>
                <div className={styles.contactGraphicsOne}>
                    <img src="/images/yellow.png" />
                </div>
                <div className={styles.contactGraphicsTwo}>
                    <img src="/images/contact-graphics.png" />
                </div>
                <div className="container">
                    <section className={styles.contactWrap}>
                        <div className="row align-items-center">
                            <div className="col-lg-6">
                                <div className={styles.topSec}>
                                    <Subtitle text={"Future Build"} />
                                    <Heading
                                        mainText={
                                            "Let’s Plan Your Future Together"
                                        }
                                    />
                                    <p>At Eduspire Global, we believe that financial uncertainty should never stand in the way of your dreams. Our team of experts helps you plan your finances, access scholarships and loans, and confidently embark on your study abroad journey.</p>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.formWrap}>
                                    {/* <form className={styles.form}>
                    <div className={styles.formGroup}>
                      <label htmlFor="firstName">First Name</label>
                      <input
                        type="text"
                        id="firstName"
                        name="firstName"
                        placeholder="Enter first name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="lastName">Last Name</label>
                      <input
                        type="text"
                        id="lastName"
                        name="lastName"
                        placeholder="Enter last name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="email">Email</label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        placeholder="Enter email"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <CommonButton text={'Submit'} />
                  </form> */}
                                    <HubspotEmbedForm />
                                </div>

                            </div>
                        </div>
                    </section>
                </div>
            </section>
            <Footer />

        </>
    );
}
