import Head from "next/head";
import styles from "@/styles/Whyuk.module.css";
import Header from "@/components/Header/Header";
import CommonButton from "@/components/CommonBtn/CommonBtn";
import Subtitle from "@/components/Subtitle/Subtitlle";
import Heading from "@/components/Heading/Heading";
import { useState } from "react";
import { FaPlus, FaMinus } from "react-icons/fa"; // npm install react-icons
import { HiMinus, HiOutlineChevronDoubleRight, HiOutlineChevronRight } from "react-icons/hi2";
import { BsPlusLg } from "react-icons/bs";
import Footer from "@/components/Footer/Footer";
import HubspotEmbedForm from "@/components/HubspotEmbedForm/HubspotEmbedForm";
import Link from "next/link";
import Modal from "@/components/Modal/Modal";

export default function WhyUK() {
    const [open, setOpen] = useState(false);
    return (
        <>
            <Head>
                <title>Why UK</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* =======banner======= */}
            <section className={styles.mainBanner}>
                <div className={styles.bannerGraphics}>
                    <img src="/images/bg-graphics.png" alt="bg-graphics" />
                </div>

                <div className="container">
                    <div className={`row justify-content-center align-items-center ${styles.bannerRow}`}
                    >
                        <div className="col-lg-7">
                            <div className={styles.bannerContent}>
                                <h1>Why UK</h1>
                                {/* Breadcrumb starts here */}
                                <nav aria-label="breadcrumb" className={styles.breadcrumbWrapper}>
                                    <ol className={styles.breadcrumb}>
                                        <li className={styles.breadcrumbItem}>
                                            <a href="/">Home</a>
                                            <span className={styles.chevron}><HiOutlineChevronRight /></span>
                                        </li>
                                        <li
                                            className={`${styles.breadcrumbItem} ${styles.active}`}
                                            aria-current="page"
                                        >
                                            Why UK
                                        </li>
                                    </ol>
                                </nav>

                                {/* Breadcrumb ends here */}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* =======why us========= */}
            <section className={styles.whyUs}>
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-6">
                            <div className={styles.leftHeading}>
                                <Subtitle text={"Why Us"} />
                                <Heading
                                    mainText={
                                        "The United Kingdom : a century long destination for Indian students"
                                    }
                                />
                            </div>
                        </div>
                        <div className="col-lg-6">
                            <div className={styles.rightItem}>
                                <p>
                                    For over 100 years, United Kingdom has been a steadfast choice
                                    for Indian students. The endless appeal of United Kingdom lies
                                    not merely in prestige and ranking, but also in the seamless
                                    confluence of quality, research and job opportunity.
                                </p>
                                <p>
                                    From the hallowed halls of Oxford, Cambridge, LSE and Imperial
                                    to the esteemed institutions like Manchester, Warwick,
                                    Glasgow, Edinburgh, SOAS, Kings College London...consistently
                                    rank among top 500 universities globally.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <Modal isOpen={open} onClose={() => setOpen(false)}>
                    <HubspotEmbedForm />
                </Modal>

                <div className={styles.eachItem} style={{ backgroundColor: "#FFEAD7" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Strong academic synergy with India</h4>
                                    <p>
                                        The Indian education system has many similarities with UK's
                                        academic framework. UK universities highly recognise the
                                        three year undergraduate academic degree program (BSc, BCom,
                                        BA, BBA, BCA), which are often not accepted in countries
                                        like USA. Similarly for undergraduate admissions, CBSE, ISC
                                        and state boards are accepted alongside international
                                        curriculum like A levels and IB,
                                    </p>
                                    <Link onClick={() => setOpen(true)} href="#!" className={styles.readMore}>Get Details <HiOutlineChevronDoubleRight /></Link>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-4.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.eachItem} style={{ backgroundColor: "#D5F6E3" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Time efficient and cost effective degree</h4>
                                    <p>
                                        Bachelor's degrees usually takes three years Master degree
                                        programs are typically one year, saving both on tuition fees
                                        and living expenses.PHD programs span 3 years
                                    </p>
                                    <Link onClick={() => setOpen(true)} href="#!" className={styles.readMore}>Get Details <HiOutlineChevronDoubleRight /></Link>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-1.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.eachItem} style={{ backgroundColor: "#E4E0FF" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Multicultural student community</h4>
                                    <p>
                                        With students from over 130 countries, international
                                        students can work upto 20 hours per week during term time
                                        and gain ample exposure to the local culture and thought
                                        process.
                                    </p>
                                    <Link onClick={() => setOpen(true)} href="#!" className={styles.readMore}>Get Details <HiOutlineChevronDoubleRight /></Link>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-2.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.eachItem} style={{ backgroundColor: "#FFD7D8" }}>
                    <div className="container">
                        <div className={`${"row align-items-center"} ${styles.row}`}>
                            <div className="col-lg-6">
                                <div className={styles.whyContent}>
                                    <h4>Financial support and post study work</h4>
                                    <p>
                                        All UK universities are recognised by Indian financial
                                        institutions (both government and private). That makes it
                                        easy for Indian students to get education loans. The
                                        Post-Study Work visa allows international students to stay
                                        back and work in UK for upto 2 years, after completion of
                                        student visa. That gives international students ample
                                        international work experience and exposure and thus empowers
                                        students to take assured steps towards a global future.
                                    </p>
                                    <Link onClick={() => setOpen(true)} href="#!" className={styles.readMore}>Get Details <HiOutlineChevronDoubleRight /></Link>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.eachImg}>
                                    <img src="/images/edi-img-3.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ==============guidence Form============ */}
            <section className={styles.guidenceForm}>
                <div className={styles.contactGraphicsOne}>
                    <img src="/images/yellow.png" />
                </div>
                <div className={styles.contactGraphicsTwo}>
                    <img src="/images/contact-graphics.png" />
                </div>
                <div className="container">
                    <section className={styles.contactWrap}>
                        <div className="row align-items-center">
                            <div className="col-lg-6">
                                <div className={styles.topSec}>
                                    <Subtitle text={"Personalised Guidance"} />
                                    <Heading
                                        mainText={
                                            "Get Personalised Guidance for Your UK or Ireland University Journey"
                                        }
                                    />
                                    <p>Have questions about university admissions, course selection, or visa applications? Our experienced team at EdusoireGlobal is here to support you every step of the way. Fill out the form below and let us help you make the right choices for your future.</p>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className={styles.formWrap}>
                                    {/* <form className={styles.form}>
                    <div className={styles.formGroup}>
                      <label htmlFor="firstName">First Name</label>
                      <input
                        type="text"
                        id="firstName"
                        name="firstName"
                        placeholder="Enter first name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="lastName">Last Name</label>
                      <input
                        type="text"
                        id="lastName"
                        name="lastName"
                        placeholder="Enter last name"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <div className={styles.formGroup}>
                      <label htmlFor="email">Email</label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        placeholder="Enter email"
                        className={styles.eachInput}
                        required
                      />
                    </div>

                    <CommonButton text={'Submit'} />
                  </form> */}
                                    <HubspotEmbedForm />
                                </div>

                            </div>
                        </div>
                    </section>
                </div>
            </section>

            <Footer />

        </>
    );
}
